- name: Get the storageclass {{ default_storageclass }}
  k8s_info:
    api_version: storage.k8s.io/v1
    kind: StorageClass
    name: "{{ default_storageclass }}"
  register: reg_storageclass

- debug: var=reg_storageclass

- name: Set the storageclass {{ default_storageclass }} as default
  command: >-
    oc patch storageclass {{ default_storageclass }} --type merge
    --patch='{"metadata":{"annotations":{"storageclass.kubernetes.io/is-default-class":"true"}}}'
  when:
    - reg_storageclass.resources[0]['annotations']['storageclass.kubernetes.io/is-default-class'] is defined
    - reg_storageclass.resources[0]['annotations']['storageclass.kubernetes.io/is-default-class'] == "true"

